wladder/config/routes.rb
Rails.application.routes.draw do

root "home#index"
get 'query',to:"home#show"
end

wladder/app/controllers/home_controller.rb
class HomeController < ApplicationController

 def index

 end


 def show
   @words = Array.new
   if params[:step1] != ""
     @words.push(params[:step1])
   end
   if params[:step2] != ""
     @words.push(params[:step2])
   end
   if params[:step3] != ""
     @words.push(params[:step3])
   end
   if params[:step4] != ""
     @words.push(params[:step4])
   end
   if params[:step5] != ""
     @words.push(params[:step5])
   end
   @validWord = true
   @words.each_with_index { |x,i| 
     if i == 0
       @validWord = edit_distance_of_one params[:startWord], x
     elsif i != @words.length-1
       @validWord = edit_distance_of_one @words[i-1], x 
     else
       @validWord = edit_distance_of_one x, params[:endWord]
     end
   }
   if @words.length == 0
     @validWord = false
   end
   @startWord = params[:startWord]
   @endWord = params[:endWord]
 end
end

wladder/app/views/home/index.html.erb
<h1>Word Ladder Game</h1>
<h3>Adam J. Penn</h3>
<% load "#{Rails.root}/lib/ladder.rb" %>

<%= form_tag(query_path, method: "get") do  %>
    <%@startWord = dictionary.sample%>
    <p>Start: <%=@startWord%><br>
    <%= hidden_field_tag(:startWord, value = @startWord)%>
    Step 1: <%= text_field_tag(:step1) %><br>
    Step 2: <%= text_field_tag(:step2) %><br>
    Step 3: <%= text_field_tag(:step3) %><br>
    Step 4: <%= text_field_tag(:step4) %><br>
    Step 5: <%= text_field_tag(:step5) %><br>
    <%@endWord = dictionary.sample%>
    End: <%=@endWord%> 
    <%= hidden_field_tag(:endWord, value = @endWord) %>
    <%= submit_tag("Try") %></p>
<% end %>

wladder/app/views/home/show.html.erb
<a href="http://162.243.158.152/wladder">Play Again</a>
<br>
<%if @validInput == false%>
  <h2>you win!</h2>
<%else%>
  <h2>you lose!</h2>
<%end%>
<p>
  <h3>Start Word: <%=@startWord%></h3>
  <%@words.each do |x| %>
  <%=x%><br>
  <%end%> 
  <h3>End Word: <%=@endWord%></h3>
</p>

wladder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wladder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>