wbib/config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :references, shallow: true
  end
  
  root 'topics#index'

end

wbib/app/models/reference.rb
class Reference < ActiveRecord::Base
  
  belongs_to :topic

  validates :URL, format: { with: /^https?:\/\//, message: "only valid websites allowes, use http://", :multiline => true }
end

wbib/app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :references, dependent: :destroy
end

wbib/app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:edit, :update, :destroy]
  def index
    @topic = Topic.find params[:topic_id]
    @references = @topic.references
  end
  
  def new
    @topic = Topic.find params[:topic_id]
    @reference = @topic.references.new
  end
  
  def edit
  end
  
  def create
    @topic = Topic.find params[:topic_id]
    @reference = @topic.references.new(reference_params)
    if @reference.save
      redirect_to topic_references_url(@topic), notice: 'Reference created'
    else
      render :new
    end
  end

  def update
    if @reference.update(reference_params)
      redirect_to topic_references_url(@reference.topic), notice: 'Reference Updated'
    else
      render :edit
    end
  end

  def destroy
    @reference.destroy
    redirect_to topic_references_url(@reference.topic), notice: 'Reference deleted'
  end

  private
    def set_reference
      @reference = Reference.find(params[:id])
    end

    def reference_params
      params.require(:reference).permit(:URL, :time)
    end
  
end

wbib/app/controllers/topics_controller.rb
class TopicsController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_topic,  only: [:show, :edit, :update, :destroy]
  
  def index
    @topics = Topic.all
  end

  def show
    redirect_to topics_url
    #@references = @topic.references
  end

  def new 
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_url, notice: 'Topic was updated successfully'
    else 
      render :edit
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_url
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

wbib/app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="Error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>
     
      <ul>
      <% @topic.error.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <br><%= f.submit %>
  </div>
<% end %>

wbib/app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show this Topic', @topic %> | 
<%= link_to 'Show all Topics', topics_path %>

wbib/app/views/topics/index.html.erb
<h1>Listing Topics</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="5"></th>
    <tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
	<td><%= topic.description %></td>
	<td><%= link_to 'Show', topic_references_path(topic) %></td>
	<td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= button_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

wbib/app/views/topics/new.html.erb
<h1>New Topic</h1>
  
<%= render 'form' %>

<%= link_to 'Back', topics_path %>

wbib/app/views/topics/show.html.erb
<h1>Listing Topics</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="5"></th>
    <tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
	<td><%= topic.description %></td>
	<td><%= link_to 'Show', topic_references_path(topic) %></td>
	<td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= button_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>