img/config/routes.rb
Rails.application.routes.draw do
  resources :image_users
  devise_for :users
  resources :tags
  resources :images
  
  resources :image do
    resources :tag, :shallow => true
    resources :image_users, :shallow => true
  end

  root 'images#index'

end

img/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user 
  has_many :tags
  has_many :users, through: :imageuser
  accepts_nested_attributes_for :tags
  

  # got algorithm from http://stackoverflow.com/questions/88311/how-best-to-generate-a-random-string-in-ruby
  def generate_filename
    string = (0...8).map { (65 + rand(26)).chr }.join
    string = string + ".jpg"
    return string
  end
end

img/app/models/image_user.rb
class ImageUser < ActiveRecord::Base
  belongs_to :User
  belongs_to :Image
end

img/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :image
end

img/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_many :images, dependent: :destroy
  has_many :imageusers, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

img/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

img/app/controllers/image_users_controller.rb
class ImageUsersController < ApplicationController
  before_action :set_image_user, only: [:show, :edit, :update, :destroy]

  # GET /image_users
  # GET /image_users.json
  def index
    @image_users = ImageUser.all
  end

  # GET /image_users/1
  # GET /image_users/1.json
  def show
  end

  # GET /image_users/new
  def new
    @image_user = ImageUser.new
  end

  # GET /image_users/1/edit
  def edit
  end

  # POST /image_users
  # POST /image_users.json
  def create
    @image_user = ImageUser.new(image_user_params)

    respond_to do |format|
      if @image_user.save
        format.html { redirect_to image_url(@image_user.image_id), notice: 'Image user was successfully created.' }
        format.json { render :show, status: :created, location: @image_user }
      else
        format.html { render :new }
        format.json { render json: @image_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_users/1
  # PATCH/PUT /image_users/1.json
  def update
    respond_to do |format|
      if @image_user.update(image_user_params)
        format.html { redirect_to @image_user, notice: 'Image user was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_user }
      else
        format.html { render :edit }
        format.json { render json: @image_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_users/1
  # DELETE /image_users/1.json
  def destroy
    @image_user.destroy
    respond_to do |format|
      format.html { redirect_to image_url(@image_user.image_id), notice: 'Image user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_user
      @image_user = ImageUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_user_params
      params.require(:image_user).permit(:image_id, :user_id)
    end
end

img/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
    @imageusers = ImageUser.all
    @users = User.all
   end

  # GET /images/1
  # GET /images/1.json
  def show
    @tag = Tag.new
    @users = User.all
    @tags = Tag.all
    @imageusers = ImageUser.all
    @imageuser = ImageUser.new
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.filename = generate_filename
    @image.user_id = current_user.id

    @uploaded_io = params[:image][:uploaded_file]

    File.open(Rails.root.join('public', 'images', @image.filename), 'wb') do |file|
        file.write(@uploaded_io.read)
    end

    if @image.save
      redirect_to @image, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  def generate_filename
    # got algorithm from http://stackoverflow.com/questions/88311/how-best-to-generate-a-random-string-in-ruby
    notUnique = true
    while notUnique
      notUnique = false
      string = (0...8).map { (65 + rand(26)).chr }.join
      string = string + ".jpg"
      images = Image.all
	images.each do |image|
        if image.filename == string
	  notUnique = true
	end
      end
    end
    return string
   end
  

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:filename, :private, :user_id)
    end
end

img/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to image_url(@tag.image_id), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to image_url(@tag.image_id), notice: 'Tag was successfully updated.' }
        format.json { render image(@tag.image_id), status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to image_url(@tag.image_id), notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:str, :image_id)
    end
end

img/app/helpers/image_users_helper.rb
module ImageUsersHelper
end

img/app/helpers/images_helper.rb
module ImagesHelper
end

img/app/helpers/tags_helper.rb
module TagsHelper
end

img/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :private %>?
    <%= f.check_box :private %><br>
  </div>
  <div class="field">
    <%= f.file_field :uploaded_file %><br>
  </div>
  <div class="actions">
  <%= f.submit %>
  </div>
<% end %>

img/app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

img/app/views/images/index.html.erb
<p id="notice"><%= notice %></p>


<!--nav bar -->
<% if user_signed_in? %>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Social Image Network</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="#public">Public Images</a></li>
          <li><a href="#youOwn">Images You Own</a></li>
          <li><a href="#shared">Images Shared With You</a></li>
	  <li><%= link_to 'New Image', new_image_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>
<style>
.navbar-default {
  background-color: #000000;
  border-color: #5e5e5e;
}
.navbar-default .navbar-brand {
  color: #787878;
}
.navbar-default .navbar-brand:hover, .navbar-default .navbar-brand:focus {
  color: #f6f6f6;
}
.navbar-default .navbar-text {
  color: #787878;
}
.navbar-default .navbar-nav > li > a {
  color: #787878;
}
.navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus {
  color: #f6f6f6;
}
.navbar-default .navbar-nav > li > .dropdown-menu {
  background-color: #000000;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > a {
  color: #787878;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > a:hover,
.navbar-default .navbar-nav > li > .dropdown-menu > li > a:focus {
  color: #f6f6f6;
  background-color: #5e5e5e;
}
.navbar-default .navbar-nav > li > .dropdown-menu > li > .divider {
  background-color: #000000;
}
.navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:hover, .navbar-default .navbar-nav > .active > a:focus {
  color: #f6f6f6;
  background-color: #5e5e5e;
}
.navbar-default .navbar-nav > .open > a, .navbar-default .navbar-nav > .open > a:hover, .navbar-default .navbar-nav > .open > a:focus {
  color: #f6f6f6;
  background-color: #5e5e5e;
}
.navbar-default .navbar-toggle {
  border-color: #5e5e5e;
}
.navbar-default .navbar-toggle:hover, .navbar-default .navbar-toggle:focus {
  background-color: #5e5e5e;
}
.navbar-default .navbar-toggle .icon-bar {
  background-color: #787878;
}
.navbar-default .navbar-collapse,
.navbar-default .navbar-form {
  border-color: #787878;
}
.navbar-default .navbar-link {
  color: #787878;
}
.navbar-default .navbar-link:hover {
  color: #f6f6f6;
}

@media (max-width: 767px) {
  .navbar-fixed-top {
    position: relative;
    top: auto;
  }
  .navbar-default .navbar-nav .open .dropdown-menu > li > a {
    color: #787878;
  }
  .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover, .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #f6f6f6;
  }
  .navbar-default .navbar-nav .open .dropdown-menu > .active > a, .navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover, .navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #f6f6f6;
    background-color: #5e5e5e;
  }
}
.image_box_own {
    display: inline-block;
    width: 100px;
    height: 100px;
    margin: 5px;
}
.image_box {
    display: inline-block;
    width: 200px;
    height: 100px;
    margin: 5px;
}
</style>
<h1 style="color:#5e5e5e">Listing Images</h1>
<hr>
<% pub = false %>
<% pri = false %>
<% sha = false %>
<% if !user_signed_in? %>
  <table>
  <% @images.each do |image| %>
    <% if image.private != true %>
      <% if !pub %>
        <h2 style="color:#5e5e5e">Public Images</h2>
        <% pub = true %>
      <% end %>
      <div class="image_box custom_font">
        <%= link_to image do %>
          <%= image_tag root_url + "/images/" + image.filename, size: "100x100", alt: image.filename %>  
        <% end %>
        <% @users.each do |user| %>
          <% if user.id == image.user_id %>
            <a style="color:#5e5e5e"><%= user.name %></a>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <a name="public"></a>
  <% @images.each do |image| %>
    <% if image.private != true and image.user_id != current_user.id %>
      <% if !pub %>
        <h2 style="color:#5e5e5e">Public Images</h2>
        <% pub = true %>
      <% end %>
      <div class="image_box">
        <%= link_to image do %>
          <%= image_tag root_url + "/images/" + image.filename, size: "100x100", alt: image.filename %>  
        <% end %>
        <% @users.each do |user| %>
          <% if user.id == image.user_id %>
            <a style="color:#5e5e5e"><%= user.name %></a>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <hr>
  <a name="youOwn"></a>
  <% @images.each do |image| %>
    <%if image.user_id ==  current_user.id %>
      <% if !pri %>
        <h2 style="color:#5e5e5e">Images you own</h2>
        <% pri = true %>
      <% end %>
      <div class="image_box_own">
        <%= link_to image do %>
          <%= image_tag root_url + "/images/" + image.filename, size: "100x100", alt: image.filename %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <hr>
  <a name="shared"></a>
  <% @imageusers.each do |imageuser| %>
    <%if imageuser.user_id == current_user.id %>
      <% @images.each do |image| %>
        <% if !sha %>
          <h2 style="color:#5e5e5e">Images shared with you</h2>
          <% sha = true %>
        <% end %>
        <% if image.private == true and imageuser.image_id == image.id %>
          <div class="image_box">
            <%= link_to image do %>
              <%= image_tag root_url + "/images/" + image.filename, size: "100x100", alt: image.filename %>
            <% end %>
            <% @users.each do |user| %>
              <% if user.id == image.user_id %>
                <a style="color:#5e5e5e"><%= user.name %></a>
              <% end %>
            <% end %>
	  </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <br><br>

  <hr>

<% end %>

img/app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

img/app/views/images/show.html.erb
<p style="color:#6e5e5e" id="notice"><%= notice %></p>
<p>
  <%= image_tag root_url + "/images/" + @image.filename, size: "400x400", alt: @image.filename %>
</p>
<p style="color:#5e5e5e">
<strong>Owner:</strong>
<% @users.each do |user| %>
  <% if user.id == @image.user_id %>
    <%= user.name %>
  <% end %>
<% end %>
</p>
<hr>
<p style="color:#5e5e5e">
<strong>Tags:</strong><br>
<% @tags.each do |tag| %>
  <% if tag.image_id == @image.id %>
    <%= tag.str %>
    <% if @image.user_id == current_user.id %>
      <%= link_to 'Edit', edit_tag_path(tag) %> |
      <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <br>
  <% end %>
<% end %>
</p>
<% if user_signed_in? && @image.user_id == current_user.id %>
  <div style="color:#5e5e5e" class="field">
    <%= form_for @tag do |f| %>
      <p><b>New tag:</b></p>
      <%= f.text_field :str %>
      <%= f.hidden_field :image_id ,:value => @image.id %>
      <%= f.submit %>
    <% end %> 
  </div>
  <hr>
  <% if @image.private %>
    <p style="color:#5e5e5e">
    <strong>Shared with:</strong><br>
    <% notShareWith = Array.new %>
    <% @users.each do |user| %>
      <% notShareWith.push(user) %>
    <% end %>
    <% shareWith = Array.new %>
    <% @imageusers.each do |imageuser| %>
      <% if imageuser.image_id == @image.id %>
        <% @users.each do |user| %>
          <% if imageuser.user_id == user.id %>
            <%= user.name+" "+user.email %>
	    <%= link_to 'Revoke Access', imageuser, method: :delete, data: { confirm: 'Are you sure?' } %><br>
            <% shareWith.push(user) %>
  	  <% end %>
        <% end %>
      <% end %>
    <% end %>
    <% shareWith.each do |sw| %>
      <% index = notShareWith.index(sw) %>
      <% if index %>
        <% notShareWith.delete_at(index) %>
      <% end %>
    <% end %>
    <% @users.each do |user| %>
      <% if user.id == current_user.id %>
        <% notShareWith.delete_at(notShareWith.index(user)) %>
      <% end %>
    <% end %>
    <br><b>Share with other user:</b><br>
    <%= form_for @imageuser do |f| %>
      <%= f.select :user_id, options_from_collection_for_select(notShareWith, 'id', 'name'), prompt: 'Select user to add' %>
      <%= f.hidden_field :image_id ,:value => @image.id %>
      <%= f.submit %>
    <% end %>
    <hr>
  <% end %>
  <style>
    .box {
      display: inline-block;
      width: 300px;
      height: 20px;
      margin: 3px;
      color: #5e5e5e;
    }
  </style>
  <div class="box">
    <strong >Edit Image Option:</strong><br>
    <%= form_for(@image) do |f| %>
      <div class="field">
        <%= link_to 'Delete Image',@image, method: :delete, data: { confirm: 'Are you sure?' } %> |
        <b>Make</b> <%= f.label :private %>
        <%= f.check_box :private %><br>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
<% end %>
</p>
<hr>
<%= link_to 'Back', images_path %>

img/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<body background="http://hdwallpaperbook.com/wp-content/gallery/images-for-website-background/free_web_background_3_by_kgombocka-d4gz4lh.jpg">
<div style="color:#5e5e5e" id="user_nav">
<% if user_signed_in? %>
  Signed in as <%= current_user.name %>. Not you?
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> or
  <%= link_to "Sign in", new_user_session_path %>
<% end %>
</div>

<head>
  <title>Img</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

</html>

img/app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2 style="color:#5e5e5e"><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul style="color:#5e5e5e">
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="color:#5e5e5e" class="field">
    <%= f.label :str %><br>
    <%= f.text_field :str %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

img/app/views/tags/edit.html.erb
<h1 style="color:#5e5e5e">Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', image_path(@tag.image_id) %>

img/app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Str</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.str %></td>
        <td><%= tag.image_id %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

img/app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', image_url(@image) %>

img/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Str:</strong>
  <%= @tag.str %>
</p>

<p>
  <strong>Image:</strong>
  <%= @tag.image_id %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>